#!/usr/bin/python
# Import required libraries
import numpy as np



def iMatrix(n):
    """
    Function that creates an identify matrix at any size    
    """
    print n
    matrix = np.zeros((n,n))

    for k in range(n):
        matrix[k,k] = 1

    return matrix


print iMatrix(3)


### EOF ###